sonar.organization=dhanigasree
sonar.projectKey=Dhanigasree_ChargeOps
sonar.projectName=ChargeOps
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true

sonar.sources=ev-backend,ev-frontend

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,.github/**,terraform-eks/**,k8s/**,argocd/**

sonar.javascript.lcov.reportPaths=ev-frontend/coverage/lcov.info,ev-backend/services/*/coverage/lcov.info
