apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - storageclass.yaml
  - configmap.yaml
  - secrets.yaml
  - network-policies.yaml
  - ai-service.yaml
  - api-gateway.yaml
  - backend-services.yaml
  - mongodb.yaml
  - frontend.yaml
  - ingress.yaml
