apiVersion: v1
kind: Secret
metadata:
  name: ai-service-secret
  namespace: prod
  annotations:
    chargeops.io/source: aws-secrets-manager
    chargeops.io/kms-encrypted: "true"
type: Opaque
stringData:
  MONGODB_SECRET_ID: chargeops/prod/ai-service/mongodb
