name: CD - auth-service
 
on:
  push:
    branches: [dev, main]
    paths:
      - "ev-backend/services/auth-service/**"

permissions:
  contents: write

jobs:
  cd:
    name: Run CD template
    uses: ./.github/workflows/cd-backend-template.yaml
    with:
      service: auth-service
      working_directory: ev-backend/services/auth-service
      k8s_manifest_path: k8s/dev/auth-service/rollout.yaml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

