name: CD - frontend

on: 
  push:
    branches: [dev, main]
    paths:
      - "ev-frontend/**"

permissions:
  contents: write

jobs:
  cd:
    name: Run CD template
    uses: ./.github/workflows/cd-backend-template.yaml
    with:
      service: frontend
      working_directory: ev-frontend
      k8s_manifest_path: k8s/dev/frontend/rollout.yaml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

