name: CD - station-service
 
on:
  push:
    branches: [dev, main]
    paths:
      - "ev-backend/services/station-service/**"

permissions:
  contents: write

jobs:
  cd:
    name: Run CD template
    uses: ./.github/workflows/cd-backend-template.yaml
    with:
      service: station-service
      working_directory: ev-backend/services/station-service
      k8s_manifest_path: k8s/dev/station-service/deployment.yaml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

